### ISSUE TITLE
Missing dependency `readable-stream`

### ISSUE THREAD

**Issue by emilbayes** [AndreasMadsen/endpoint#1]
So I just took `denmark-io/denmark-dawa` for a spin in the browser, but `endpoint` [conditionally depends](https://github.com/AndreasMadsen/endpoint/blob/b572f5fc4fba764b3cb36fa42efe8f81aed9b983/endpoint.js#L7) on `readable-stream`.

I'm not sure if `readable-stream` should be a `dependency`, `peerDependency` (not sure of their purpose anymore) or something else.

**Comment by AndreasMadsen** [comment]
Oh, lets just remove that. browserify should take care of that.

**Comment by AndreasMadsen** [comment]
fixed!
