### ISSUE TITLE
limit option

### ISSUE THREAD

**Issue by emilbayes** [AndreasMadsen/endpoint#3]
Can I add a limit option to restrict the number of bytes it will allow?

**Comment by AndreasMadsen** [comment]
Perhaps [`slicepoint(0, limit)`](https://github.com/AndreasMadsen/slicepoint)`.pipe(endpoint(cb))` is what you are looking for? 

_edit: also, aren't there now like a 100+ of these modules, surely one of them has a limit feature._

**Comment by emilbayes** [comment]
The world needs another one https://github.com/emilbayes/secure-concat

**Comment by AndreasMadsen** [comment]
:D Is it really moral to create more concat-stream modules? I'm only allowed because this was one of the first. Also `slicepoint` is a superior module, learn it, live it, obey it.
